### ISSUE TITLE
Setup DNS entries of actual domain to work without the on-the-fly server

### ISSUE THREAD

**Issue by martinheidegger** [dnslink-std/test#2]
While `dnslink-test` does come with a [on-the-fly](https://github.com/dnslink-std/test/issues/1) dns server, that contains all the dns settings required to run the tests, it would also be important to setup the actual DNS settings of the domains used in the test in case an implementation is not able to configure the dns settins to use the on-the-fly server.

All dns settings required are defined in `dns` methods of [`integration-tests.js`](https://github.com/dnslink-std/test/blob/main/integration-tests.js), for example:

```javascript
't02: A domain without a _dnslink subdomain, containing one valid ipfs link, should return that link.': {
    dns: domain => ({
      [domain]: ['dnslink=/ipfs/ABCD']
    }),
```

Here `domain` is the `t02.dnslink.dev` endpoint meaning: to run this test we need the TXT entry of `t02.dnslink.dev TXT dnslink=/ipfs/ABCD`.

@lidel How can we set the entries best?

**Comment by lidel** [comment]
iirc `dnslink.dev` is owned and managed by Protocol Labs, so either:
- (A) we do it manually as ad-hoc one time thing (I open an internal ticket for setting them up)
- (B) we attach `DNSIMPLE_TOKEN` to this repo and set up CI job for updating records via something like [dnslink-dnsimple](https://www.npmjs.com/package/dnslink-dnsimple) (this would be handy because we could add more test cases via simple PR, but not sure how feasible it is permission-wise)
   - @mburns  is it possible to create a  `DNSIMPLE_TOKEN`  that has only access to `dnslink.dev`?  (We would like to use it in this repo + move https://github.com/ipfs/dnslink-website/ to this org at some point as well)

**Comment by martinheidegger** [comment]
Automation is a bit more effort, but it seems the way to go. This way we can make sure that any PR on this repository merged is also deployed.

I invited @mburns as owner to the `dnslink-std` organization to add eventual secrets.

**Comment by martinheidegger** [comment]
@lidel @mburns I added with PR #3 a script that should be able to update the necessary `dnslink.dev` entries. Tested against the sandbox API.

**Comment by mburns** [comment]
>     * @mburns  is it possible to create a  `DNSIMPLE_TOKEN`  that has only access to `dnslink.dev`?  (We would like to use it in this repo + move https://github.com/ipfs/dnslink-website/ to this org at some point as well)

DNSimple doesn't provide granular tokens like that, unfortunately. We could limit it with a separate account, or if needed a separate provider.

**Comment by lidel** [comment]
Ack. Mind creating a separate account for dnslink and move `dnslink.io` and `dnslink.dev` there? (I don't have necessary permissions)
